# These are supported funding model platforms

github: julianYaman
patreon: yaman071
custom: ['https://www.buymeacoffee.com/julianyaman', 'https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=SJHABMNBYCTBC&source=url']
